repos:
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.2
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate
    -   id: terraform_tflint
        args:
           - --args=--format=compact
    -   id: terraform_docs
        args:
           - --args=--config=.terraform-docs-config.yaml