apiVersion: v1
kind: Secret
metadata:
  name: odoo-secrets
type: Opaque
data:
  odoo-password: YWRtaW4=
  password: eW91cl9wb3N0Z3Jlc19wYXNzd29yZA==
  postgres-password: eW91cl9wb3N0Z3Jlc19wYXNzd29yZA==
  username: Ym5fb2Rvbw==
  database: Yml0bmFtaV9vZG9v
