apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: smartbuilding-ns
data:
  APP_PORT_FRONT: "8080"
  MERCURE_URL: "http://mercure-service.smartbuilding-ns.svc.cluster.local"
  MERCURE_PUBLIC_URL: "http://mercure-service.smartbuilding-ns.svc.cluster.local"
  SERVER_NAME: "smartbuilding.local"
  HTTP_PORT: "80"
  HTTPS_PORT: "443"
  HTTP3_PORT: "443"
  APP_DB_ADMIN_PORT: "8081"
  DB_PORT: "3306"
  MYSQL_DB: "smartbuilding"