apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: smartbuilding-ns
stringData:
  MERCURE_JWT_SECRET: "your-secret-key"
  MERCURE_PUBLISHER_JWT_KEY: "your-publisher-key"
  MERCURE_SUBSCRIBER_JWT_KEY: "your-subscriber-key"
  JWT_PASSPHRASE: "your-strong-jwt-passphrase"  # Added for JWT
  APP_SECRET: "your-app-secret"                 # Added for Symfony
  DATABASE_URL: "mysql://dbuser:dbpassword@database:3306/smartbuilding?serverVersion=mariadb-10.11"  # Added for Doctrine
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: smartbuilding-ns
stringData:
  MYSQL_ROOT_PASS: "rootpassword"
  MYSQL_USER: "dbuser"
  MYSQL_PASS: "dbpassword"
