apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: smartbuilding-ns
  labels:
    app: backend
    component: backend
spec:
  replicas: 2  # Increased for better availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        component: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
    spec:
      containers:
      - name: backend
        image: nabilbs/smartbuilding-backend-php:latest
        ports:
        - containerPort: 9000
          name: http
        env:
        - name: DATABASE_HOST
          value: "database.smartbuilding-ns.svc.cluster.local"
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_NAME
          value: "smartbuilding"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_PASS
        # Add other environment variables from configMap and secrets
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: php-socket
          mountPath: /var/run/php
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /health
            port: 9000
          failureThreshold: 30
          periodSeconds: 10
      volumes:
      - name: php-socket
        emptyDir: {}
      # Add any other volumes needed

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: smartbuilding-ns
  labels:
    app: backend
    component: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
  # Uncomment if you need to expose this outside the cluster
  # type: LoadBalancer
  # externalTrafficPolicy: Local
