# Set replicas to a fixed number (3 for HA)
replicas: 3

# Increase resource requests/limits
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

# Configure pod anti-affinity more strictly
antiAffinity: required  # Changed from preferred to required
topologyKey: kubernetes.io/hostname

# Adjust probes for better stability
startupProbe:
  timeoutSeconds: 10
  periodSeconds: 10
  failureThreshold: 30  # Give up to 5 minutes to start

livenessProbe:
  initialDelaySeconds: 60  # Wait 1 minute before starting checks
  timeoutSeconds: 10
  periodSeconds: 30
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 30
  failureThreshold: 3

# Enable additional trusted CAs if using private certificates
additionalTrustedCAs: true  # Ensure you've created the tls-ca-additional secret

# Configure persistence more robustly
customLogos:
  enabled: true
  volumeKind: persistentVolumeClaim
  storageClass: "longhorn"
  accessMode: ReadWriteMany  # Changed to ReadWriteMany for multi-replica access
  size: 5Gi  # Increased from 2Gi

# Disable HTTP service to force HTTPS
service:
  type: ClusterIP
  disableHTTP: true  # Force HTTPS only

ingress:
  servicePort: 443  # Must match service.disableHTTP=true
