# Additional Trusted CAs.
additionalTrustedCAs: false

# Improved anti-affinity settings to spread across failure domains
antiAffinity: required
topologyKey: topology.kubernetes.io/zone

# Audit Logs with conservative settings
auditLog:
  destination: sidecar
  hostPath: /var/log/rancher/audit/
  level: 1
  maxAge: 7
  maxBackup: 3
  maxSize: 50

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  image:
    repository: "rancher/mirrored-bci-micro"
    tag: 15.6.24.2
    pullPolicy: "IfNotPresent"

# Required for legacy support
addLocal: "true"

# Debug mode should be off in production
debug: true

# Strict TLS validation
agentTLSMode: ""

# Fully qualified name to reach your Rancher server
hostname: rancher.service.r2b001.site

imagePullSecrets: []

### ingress ###
ingress:
  enabled: true
  includeDefaultExtraAnnotations: true
  ingressClassName: "nginx"
  pathType: ImplementationSpecific
  path: "/"
  servicePort: 80

  tls:
    source: "rancher"
    secretName: tls-rancher-ingress-psdhq

### service ###
service:
  type: ClusterIP
  annotations: {}
  disableHTTP: false

letsEncrypt:
  environment: ""
  ingress:
    class: ""
privateCA: false

# Network configuration
noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local

# Image settings
rancherImage: rancher/rancher

replicas: 1

# Critical priority
priorityClassName: rancher-critical

# Resource requirements for stability
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

tls: ingress

systemDefaultRegistry: ""

# Use bundled charts for consistency
useBundledSystemChart: true

# Custom logos persistence
customLogos:
  enabled: true
  volumeSubpaths:
    emberUi: "ember"
    vueUi: "vue"
  volumeKind: persistentVolumeClaim
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: 20Gi

# Post-delete hook
postDelete:
  enabled: true
  image:
    repository: rancher/shell
    tag: v0.4.1
  namespaceList:
    - cattle-fleet-system
    - cattle-system
    - rancher-operator-system
  timeout: 300
  ignoreTimeoutError: false

# Bootstrap password
bootstrapPassword: "admin"

# More aggressive health checks
startupProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 24  # 4 minutes total

livenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 30
  failureThreshold: 5  # 2.5 minutes total

readinessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 6  # 1 minute total

# Webhook and fleet configuration
webhook: ""
fleet: ""

extraObjects: []
