global:
  defaultStorageClass: "longhorn"

image:
  repository: bitnami/odoo
  tag: 18.0.20250405-debian-12-r2
  pullPolicy: IfNotPresent

odooEmail: test@example.com
odooPassword: "test123"  # For testing only
allowEmptyPassword: false

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: odoo-test.example.com
  tls: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

persistence:
  enabled: false
  storageClass: "longhorn"
  size: 1Gi
  accessModes:
    - ReadWriteOnce

volumePermissions:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

postgresql:
  enabled: true
  auth:
    username: bn_odoo
    password: "postgres123"  # For testing only
    database: bitnami_odoo
  persistence:
    enabled: false
    storageClass: "longhorn"
    size: 1Gi
    accessModes:
      - ReadWriteOnce
  podDisruptionBudget:
    enabled: false  # Disabled for testing
  primary:
    podAnnotations:
      longhorn.io/allow-inconsistent: "true"
      longhorn.io/disable-revision-counter: "true"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi

podSecurityContext:
  enabled: true
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
  seccompProfile:
    type: "RuntimeDefault"

livenessProbe:
  enabled: true
  initialDelaySeconds: 180  # Reduced from 600 for testing
  periodSeconds: 30

readinessProbe:
  enabled: true
  initialDelaySeconds: 30

startupProbe:
  enabled: false

podAntiAffinityPreset: soft

autoscaling:
  enabled: false

networkPolicy:
  enabled: false  # Disabled for testing
