apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartbuilding-ingress
  namespace: smartbuilding-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: smartbuilding.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: phpmyadmin-service
            port:
              number: 80