apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
  namespace: longhorn-system
provisioner: driver.longhorn.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
